import type { Metadata } from "next";
import "./globals.css";
import { UserContextProvider } from "@/contexts/UserContext";
import Navbar from "@/components/_ui/Navbar";
import SnackbarProviderC from "@/contexts/SnackbarProvider";
import ThemeRegistry from "./ThemeRegistry";

// 1. Importe o novo provider
import { CompetitionProvider } from "@/contexts/CompetitionContext";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br">
            <body>
                <ThemeRegistry>
                    <SnackbarProviderC>
                        <Navbar />
                        {/* 2. Adicione o provider aqui */}
                        <CompetitionProvider>
                            <UserContextProvider>
                                <main className="flex-grow">{children}</main>
                            </UserContextProvider>
                        </CompetitionProvider>
                    </SnackbarProviderC>
                </ThemeRegistry>
            </body>
        </html>
    );
}