import type { Metadata } from "next";
import "./globals.css";
import { UserContextProvider } from "@/contexts/UserContext";
import Navbar from "@/components/_ui/Navbar";
import SnackbarProviderC from "@/contexts/SnackbarProvider";
import ThemeRegistry from "./ThemeRegistry";
import styled from "@emotion/styled";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br">
            <body>
                <ThemeRegistry>
                    <SnackbarProviderC>
                        {/* O ideal é que haja apenas um Navbar */}
                        <Navbar />

                        <UserContextProvider>
                            <main className="flex-grow">{children}</main>
                        </UserContextProvider>
                    </SnackbarProviderC>
                </ThemeRegistry>
            </body>
        </html>
    );
}
